- app/utils/populateTraceLink.ts
- package-lock.json
- package.json
When TRACE_LINK isn't defined, some of the calls to populateTraceLink might be with a blank string. This makes populateTraceLink throw when trying to construct a new URL. The fix is to test with a negation instead.
(I also defined `name` under package.json)
> fix blank tracelink behaviour

- app/durableObjects/ChatRoom.server.ts
- remix.config.js
Discovered that we can use cloudflare:workers if we add it to serverDependenciesToBundle in remix.config.js. Rewrote the ChatRoom DO to use that.
> use DurableObject from cloudflare:workers

- app/components/AlertDialog.tsx
I accidentally removed this destructuring in https://github.com/cloudflare/orange/pull/46, bringing it back
> don't spread classname into AlertDialog.Content

- app/utils/rxjs/RxjsPeer.client.ts
This PR uses SDP munging to enable DTX on the Opus audio tracks.
Utilizing DTX saves bandwidth, as it saves bandwidth when the microphone isn't recording anything locally and sends a special empty Opus packet instead.
> Enable Opus DTX for audio tracks

- app/routes/_index.tsx
Right now, the content box does not have a minimum width on desktop. If the pane gets collapsed, the entire content box becomes bigger.
Before:
After:
> chore(): Set a min-width on desktop to have a static size

- app/durableObjects/ChatRoom.server.ts
> Use `this.ctx.storage` to store session data

- app/durableObjects/ChatRoom.server.ts
Now that we've fixed the issue where users connecting should try to look up an existing session before creating a new one, we should restore this
> Restore onError handler in server

- app/utils/rxjs/RxjsPeer.client.ts
As we switch Orange to the new API we no longer need to start a session with an inactive transceiver to start the connection.
> Remove the initial inactive audio transceiver

- app/components/OverflowMenu.tsx
- app/components/Participant.tsx
- app/hooks/useRoomContext.ts
- app/routes/_room.$roomName.room.tsx
- app/routes/_room.tsx
When enabled, this will stop pulling video tracks from other users—but only their webcams. Screensharing will still be pulled since it is more critical to understanding.
> Add data saver mode

- app/components/Participant.tsx
- app/components/PullAudioTracks.tsx
- app/routes/_room.$roomName.room.tsx
Putting this under the same keyboard shortcut ⌃d
> Add mid debug info

- app/components/Participant.tsx
This will show the orange outline around a participant when they've got their hand raised!
> Highlight participant window when hand is raised

- app/durableObjects/ChatRoom.server.ts
- app/utils/logging.ts
This PR adds a couple more spots to capture some data for debugging. My theory for the mystery user/users leaving is that our cleanup function is removing users when it shouldn't be, and they immediately reconnect. I've added logging so we can see the websocket states when the cleanup runs since this is how partyserver determines which connections to return in `getConnections()`
See https://github.com/threepointone/partyserver/blob/main/packages/partyserver/src/connection.ts#L167-L183
> Split error logging from details

- wrangler.development.toml
- wrangler.production.toml
- wrangler.public.toml
- wrangler.staging.toml
- wrangler.toml
`/new` was broken because nanoid was using `Buffer`, so bumping the node_compat date to fix.
> Bump node compat date

- app/durableObjects/ChatRoom.server.ts
- app/hooks/useRoom.ts
- app/types/Messages.ts
This PR removes the websocket connection checks in the alarm, and instead looks for a heartbeat timestamp to evaluate whether or not to consider a user "timed out". This should hopefully resolve the issue we've seen for a while where sometimes random users are "timed out" incorrectly.
> Restructure connection checks to look for heartbeat timestamps

- app/durableObjects/ChatRoom.server.ts
- app/utils/openai.server.ts
We're already passing `correlationId` from browser side to help debug all sessions in a call, adding it now from the durable object when it creates calls sessions and tracks for the OpenAI integration.
> Provide extra API params and correlation id for openai API calls

- app/components/ParticipantLayout.tsx
Since we need to make sure that changing participant causes everything to unmount/remount, each one should have a key
> Ensure each participant has key

- app/hooks/useDeadPulledTrackMonitor.tsx
- app/hooks/useUserMedia.ts
Inaudible track has some (inaudible) generated noise on it so that it sends a little bit more traffic to keep the transport alive.
> Use inaudible track instead of muted

- app/utils/rxjs/inaudibleAudioTrack$.ts
Setting gain to 0.01 had a strange effect that I only noticed after merging. I couldn't hear it even with my volume all the way up, UNLESS I turned my volume down, then turned it up again.
Setting gain to 0 alleviates this issue and still sends packets on the track.
> Set gain to 0

- app/hooks/useUserMedia.ts
As much as I wanted to have mute on by default in dev env, it's causing issues w/ our "inaudible" track since generating it w/ the web audio API requires a user interaction.
If we _have_ to have some user interaction, we might as well just revert this change and let the required interaction be that you need to mute yourself manually in dev.
Hopefully some day we can go back to mute by default in dev. 😵‍💫
> Revert muting by default in dev env

- app/routes/_room.tsx
This method has better cross-browser support and gets at the same information
> Get dimensions from settings instead of capabilities
